language: node_js
node_js:
  - "stable"
script:
 - yarn build
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  slack: nuphilosophy:DF9RFkQP3ojK6NqRPY0FOOSk
